services:
  trip-management:
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  mongo-trip:
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  trip-cache:
    ports:
      - "6380:6379"
