services:
  trip-management:
    build: .
    container_name: trip-management
    depends_on:
      - mongo-trip
    environment:
      - ENV_VAR=example
  mongo-trip:
      image: mongo
      restart: always
      ports:
        - 27017:27017
