name: Docker Compose Test

on:
  pull_request:
    branches: [ main, dev]

jobs:
  test-docker-compose:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Docker Compose Test
      run: |
        chmod +x ./test-docker-compose.sh
        ./test-docker-compose.sh

    - name: Upload logs if failure
      if: failure()
      run: |
        docker-compose logs > docker-compose-logs.txt

    - name: Archive logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-logs
        path: docker-compose-logs.txt
